// <auto-generated />
namespace SM.LIB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class chgeIntToString : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(chgeIntToString));
        
        string IMigrationMetadata.Id
        {
            get { return "201612131532105_chgeIntToString"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
