// <auto-generated />
namespace SM.LIB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class StudentRegChange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StudentRegChange));
        
        string IMigrationMetadata.Id
        {
            get { return "201612152316473_StudentRegChange"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
